# Generated by Django 4.1.7 on 2023-03-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
